### ISSUE TITLE
comment yaml (+empty lines?)

### ISSUE THREAD

**Issue by monouser7dig** [micro-editor/comment-plugin#17]
```yaml
# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'
```

gets commented inti
```yaml

Colors (Dracula)
# colors:
  Default colors
  # primary:
    # background: '0x282a36'
    # foreground: '0xf8f8f2'
# 
```

rather than expected 
```yaml
# Colors (Dracula)
# colors:
#   # Default colors
#   primary:
#     background: '0x282a36'
#     foreground: '0xf8f8f2'
```

furthermore: is it intended behavior to comment empty lines? Seems a bit weird to me.

**Comment by sum01** [comment]
@monouser7dig This is fixed in v1.0.6

**Comment by zyedidia** [comment]
I don't believe this is fixed unfortunately. Are you unable to reproduce?

**Comment by sum01** [comment]
Well the empty line no longer gets commented. I guess the comments being uncommented is a bit of an issue still.
